name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e-tests:
    name: Run E2E Tests with Playwright
    runs-on: ubuntu-latest

    steps:
      # 1. Vérification du code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configuration de Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Installer les dépendances
      - name: Install dependencies
        run: npm ci

      # 4. Construire l'application
      - name: Build application
        run: npm run build

      # 5. Démarrer le serveur en arrière-plan
      - name: Start server
        run: npm run start & # Le `&` permet de démarrer le serveur en arrière-plan

      # 6. Attendre que le serveur soit prêt
      - name: Wait for server to be ready
        run: npx wait-on http://localhost:3001

      # 7. Installer les navigateurs Playwright
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # 8. Exécuter les tests Playwright
      - name: Run Playwright E2E tests
        run: npx playwright test

      # 9. Upload Playwright report (optionnel)
      - name: Upload Playwright Report
        if: failure() # Exécuter uniquement en cas d'échec
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report
