name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  e2e-tests:
    name: Run E2E Tests with Playwright
    runs-on: ubuntu-latest

    steps:
      # 1. Vérification du code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Configuration de Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. Installer les dépendances
      - name: Install dependencies
        run: npm ci

      # 4. Démarrer le serveur en arrière-plan et exécuter les tests
      - name: Start server and run tests
        run: |
          npm run start & # Démarre le serveur en arrière-plan
          npx wait-on http://localhost:3001 # Attend que le serveur soit prêt
          npx playwright install --with-deps # Installe Playwright
          npx playwright test # Exécute les tests Playwright
